/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ArrowSvg: typeof import('./src/components/SvgIcons/arrowSvg.vue')['default']
    BuyButton: typeof import('./src/components/Buttons/buyButton.vue')['default']
    ElButt: typeof import('element-plus/es')['ElButt']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElementCom: typeof import('./src/components/elementCom.vue')['default']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    FooterView: typeof import('./src/components/FooterView.vue')['default']
    HeaderView: typeof import('./src/components/HeaderView.vue')['default']
    HeartSvg: typeof import('./src/components/SvgIcons/heartSvg.vue')['default']
    JordanSvg: typeof import('./src/components/SvgIcons/jordanSvg.vue')['default']
    LocationSvg: typeof import('./src/components/SvgIcons/locationSvg.vue')['default']
    MainContentView: typeof import('./src/components/MainContentView.vue')['default']
    MuteSvg: typeof import('./src/components/SvgIcons/muteSvg.vue')['default']
    NikelogoSvg: typeof import('./src/components/SvgIcons/nikelogoSvg.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchSvg: typeof import('./src/components/SvgIcons/searchSvg.vue')['default']
    ShopSvg: typeof import('./src/components/SvgIcons/shopSvg.vue')['default']
    SmallArrow: typeof import('./src/components/SvgIcons/smallArrow.vue')['default']
    Test: typeof import('./src/components/test.vue')['default']
    Test1: typeof import('./src/components/test1.vue')['default']
    UnMuteSvg: typeof import('./src/components/SvgIcons/unMuteSvg.vue')['default']
    WeChatSvg: typeof import('./src/components/SvgIcons/weChatSvg.vue')['default']
    WeiboSvg: typeof import('./src/components/SvgIcons/weiboSvg.vue')['default']
  }
}
